<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="coverlet.collector"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <ProjectReference Include="..\..\src\HVO.SkyMonitor.Deployment.Cli\HVO.SkyMonitor.Deployment.Cli.csproj" />
    <ProjectReference Include="..\..\src\HVO.SkyMonitor.Deployment.Contracts\HVO.SkyMonitor.Deployment.Contracts.csproj" />
    <ProjectReference Include="..\..\src\HVO.SkyMonitor.Deployment.Distribution\HVO.SkyMonitor.Deployment.Distribution.csproj" />
  </ItemGroup>
</Project>
