// <auto-generated />
using System;
using HVO.SkyMonitor.LogicHost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.SkyMonitor.LogicHost.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717021719_AddCentralRecoveryInventory")]
    partial class AddCentralRecoveryInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HVO.SkyMonitor.Common.Security.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<DateTimeOffset?>("ExpiresUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ExpiresAt");

                    b.Property<string>("HashedKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastUsedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HashedKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("IsActive", "ExpiresUtc");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CentralFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DevicePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ManifestSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ObjectState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ObjectVerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RecipeVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ReconciledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReconstructionState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("RecoveryGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StateReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Variant")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("StorageReference");

                    b.HasIndex("CentralFrameId", "ArtifactId")
                        .IsUnique();

                    b.HasIndex("DevicePublicId", "ArtifactId")
                        .IsUnique()
                        .HasFilter("[DevicePublicId] IS NOT NULL");

                    b.HasIndex("CentralFrameId", "Role", "RecipeVersion");

                    b.HasIndex("ObjectState", "ReconstructionState", "ReceivedAtUtc");

                    b.HasIndex("ObjectState", "RecoveryGeneration", "Id");

                    b.HasIndex("ReconstructionState", "ReceivedAtUtc", "Id");

                    b.HasIndex("ObjectState", "ObjectVerifiedAtUtc", "ReceivedAtUtc", "Id");

                    b.ToTable("CentralArtifacts", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactIngestIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ManifestSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("CentralArtifactId", "ManifestSchemaVersion")
                        .IsUnique();

                    b.ToTable("CentralArtifactIngestIdentities", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactLayout", b =>
                {
                    b.Property<Guid>("CentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BlackLevel")
                        .HasColumnType("float");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ByteOrder")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CfaPattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ContainerDepthBits")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Packing")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PixelFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SampleDepthBits")
                        .HasColumnType("int");

                    b.Property<int>("StrideBytes")
                        .HasColumnType("int");

                    b.Property<double?>("WhiteLevel")
                        .HasColumnType("float");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("CentralArtifactId");

                    b.ToTable("CentralArtifactLayouts", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactProcessingEvidence", b =>
                {
                    b.Property<Guid>("CentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlgorithmsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("CentralDerivativeJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompatibilityJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DevicePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutputIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RecipeIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RequestedRecipeIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("TotalIntegrationTicks")
                        .HasColumnType("bigint");

                    b.HasKey("CentralArtifactId");

                    b.HasIndex("CentralDerivativeJobId");

                    b.HasIndex("DevicePublicId", "OutputIdentitySha256")
                        .IsUnique();

                    b.ToTable("CentralArtifactProcessingEvidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_CentralArtifactProcessingEvidence_AttemptNumber", "[AttemptNumber] > 0");

                            t.HasCheckConstraint("CK_CentralArtifactProcessingEvidence_TotalIntegrationTicks", "[TotalIntegrationTicks] >= 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactRecipe", b =>
                {
                    b.Property<Guid>("CentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImplementationVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionsSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SemanticVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("CentralArtifactId");

                    b.ToTable("CentralArtifactRecipes", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResolvedCentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedCentralArtifactId");

                    b.HasIndex("CentralArtifactId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("CentralArtifactId", "SourceArtifactId")
                        .IsUnique();

                    b.ToTable("CentralArtifactSources", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralCaptureControl", b =>
                {
                    b.Property<Guid>("CentralFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EffectiveExposureTicks")
                        .HasColumnType("bigint");

                    b.Property<double>("EffectiveGain")
                        .HasColumnType("float");

                    b.Property<double?>("EffectiveOffset")
                        .HasColumnType("float");

                    b.Property<double?>("EffectiveTemperatureC")
                        .HasColumnType("float");

                    b.Property<long>("RequestedExposureTicks")
                        .HasColumnType("bigint");

                    b.Property<double>("RequestedGain")
                        .HasColumnType("float");

                    b.Property<double?>("RequestedOffset")
                        .HasColumnType("float");

                    b.Property<double?>("TemperatureSetpointC")
                        .HasColumnType("float");

                    b.HasKey("CentralFrameId");

                    b.ToTable("CentralCaptureControls", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralCaptureProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentralFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceRigProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRigProfileId");

                    b.HasIndex("CentralFrameId", "Kind")
                        .IsUnique();

                    b.ToTable("CentralCaptureProfiles", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralCaptureTiming", b =>
                {
                    b.Property<Guid>("CentralFrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DurableIngressUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExposureEndedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExposureStartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReadoutCompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RequestedStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SetpointAppliedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CentralFrameId");

                    b.ToTable("CentralCaptureTimings", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AvailableAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancellationRequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputSelectorJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("InputSetIdentitySha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("LastFailedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeaseAcquiredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("MissingInputOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("PredecessorJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RecipeOptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RequestedRecipeIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ResolutionCompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ResolutionDeadlineUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ResolutionStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ResultCentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RetainedResultCentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceCentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StateReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("SupersededByJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetRecipeVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TargetVariant")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorJobId")
                        .IsUnique()
                        .HasFilter("[PredecessorJobId] IS NOT NULL");

                    b.HasIndex("RequestIdentitySha256")
                        .IsUnique();

                    b.HasIndex("ResultCentralArtifactId");

                    b.HasIndex("RetainedResultCentralArtifactId");

                    b.HasIndex("SupersededByJobId");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.HasIndex("SourceCentralArtifactId", "TargetRole", "TargetRecipeVersion");

                    b.HasIndex("Status", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("Status", "LeaseExpiresAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("Status", "UpdatedAtUtc", "ResolutionDeadlineUtc", "CreatedAtUtc", "Id");

                    b.ToTable("CentralDerivativeJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_CentralDerivativeJobs_AttemptCount", "[AttemptCount] >= 0 AND [AttemptCount] <= [MaxAttempts]");

                            t.HasCheckConstraint("CK_CentralDerivativeJobs_MaxAttempts", "[MaxAttempts] > 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("CentralDerivativeJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("InputBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LeaseAcquiredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("OutputBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("RecipeDurationTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CentralDerivativeJobId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("Outcome", "LeaseExpiresAtUtc");

                    b.ToTable("CentralDerivativeJobAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CentralDerivativeJobAttempts_AttemptNumber", "[AttemptNumber] > 0");

                            t.HasCheckConstraint("CK_CentralDerivativeJobAttempts_Bytes", "[InputBytes] >= 0 AND [OutputBytes] >= 0");

                            t.HasCheckConstraint("CK_CentralDerivativeJobAttempts_RecipeDurationTicks", "[RecipeDurationTicks] >= 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<long?>("CaptureSequence")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CentralArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentralDerivativeJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentralDerivativeJobInputRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompatibilityJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompatibilitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CentralArtifactId", "CentralDerivativeJobId");

                    b.HasIndex("CentralDerivativeJobId", "CentralArtifactId")
                        .IsUnique();

                    b.HasIndex("CentralDerivativeJobId", "CentralDerivativeJobInputRequirementId")
                        .IsUnique();

                    b.HasIndex("CentralDerivativeJobId", "Ordinal")
                        .IsUnique();

                    b.ToTable("CentralDerivativeJobInputs", null, t =>
                        {
                            t.HasCheckConstraint("CK_CentralDerivativeJobInputs_ByteLength", "[ByteLength] >= 0");

                            t.HasCheckConstraint("CK_CentralDerivativeJobInputs_Ordinal", "[Ordinal] >= 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInputRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BindingName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("CentralDerivativeJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompatibilityMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ExpectedAgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ExpectedCaptureSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpectedRigId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResolutionState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SelectorJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("SequenceOffset")
                        .HasColumnType("int");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CentralDerivativeJobId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("ExpectedAgentId", "ExpectedCaptureSequence", "ResolutionState", "CentralDerivativeJobId");

                    b.ToTable("CentralDerivativeJobInputRequirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_CentralDerivativeJobInputRequirements_Ordinal", "[Ordinal] >= 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("CaptureSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CycleEvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DevicePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceRigProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FirstReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObservatoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RigId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("RigProfileVersion")
                        .HasColumnType("int");

                    b.Property<string>("SceneProvenanceJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRigProfileId");

                    b.HasIndex("AgentId", "CaptureSequence")
                        .HasFilter("[CaptureSequence] IS NOT NULL");

                    b.HasIndex("AgentId", "CapturedAtUtc");

                    b.HasIndex("DevicePublicId", "CaptureSequence")
                        .IsUnique()
                        .HasFilter("[CaptureSequence] IS NOT NULL");

                    b.HasIndex("DevicePublicId", "FrameId")
                        .IsUnique();

                    b.HasIndex("DevicePublicId", "CapturedAtUtc", "FrameId");

                    b.ToTable("CentralFrames", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralObjectRecoveryDisposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentChecksumSha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceObjectIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TargetObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SourceObjectIdentitySha256")
                        .IsUnique();

                    b.HasIndex("State", "UpdatedAtUtc", "Id");

                    b.ToTable("CentralObjectRecoveryDispositions", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralRecoveryCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long>("FindingBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("FindingCount")
                        .HasColumnType("bigint");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("InventoryStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastCompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastCycleAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastFailureAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastProgressAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NextInventoryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ObjectCursor")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("ObjectPartition")
                        .HasColumnType("int");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StagingCursor")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("StagingPartition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CentralRecoveryCheckpoints", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FindingBytes = 0L,
                            FindingCount = 0L,
                            Generation = 0L,
                            NextInventoryAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ObjectPartition = 0,
                            Phase = "Idle",
                            StagingPartition = 0
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceFleetState", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ApparentClockOffsetSeconds")
                        .HasColumnType("float");

                    b.Property<long>("BootSessionChangeCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BootSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClockDiagnostic")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("ConfigurationSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CurrentPayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("HasQuarantine")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRequiredLaneFailure")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStoragePressure")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastBootSessionChangeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSequenceGapUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReportedHealth")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long>("SequenceGapCount")
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StatusFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("AgentInstanceId")
                        .IsUnique();

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("ReportedHealth", "ReceivedAtUtc");

                    b.ToTable("DeviceFleetStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeviceFleetStates_Sequence", "[Sequence] > 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceHeartbeatRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AdvancedCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("AgentInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BootSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClockDiagnostic")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<bool>("IsSignificantSnapshot")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportedHealth")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotJson")
                        .HasMaxLength(65536)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId", "ReceivedAtUtc");

                    b.HasIndex("IsSignificantSnapshot", "ReceivedAtUtc", "Id");

                    b.HasIndex("RegistrationId", "AgentInstanceId", "Sequence")
                        .IsUnique();

                    b.ToTable("DeviceHeartbeatRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeviceHeartbeatRecords_Sequence", "[Sequence] > 0");
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceImageUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactRole")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("DevicePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ManifestSchemaVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("ObservatoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PayloadBase64Length")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RecipeVersion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RigProfileVersion")
                        .HasColumnType("int");

                    b.Property<string>("SceneProvenanceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("DevicePublicId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("ObservatoryId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("AgentId", "FrameId", "ArtifactRole", "RecipeVersion");

                    b.ToTable("DeviceImageUploads", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentRigProfileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("CurrentRigProfileUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentRigProfileVersion")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceKeyHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("DevicePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnvelopeVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("v1");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ObservatoryElevationMeters")
                        .HasColumnType("float");

                    b.Property<Guid>("ObservatoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ObservatoryLatitudeDegrees")
                        .HasColumnType("float");

                    b.Property<double>("ObservatoryLongitudeDegrees")
                        .HasColumnType("float");

                    b.Property<string>("ObservatoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ObservatoryTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OwnerConfirmationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("SelfAttested");

                    b.Property<string>("OwnerConfirmationNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("OwnerConfirmedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OwnerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RegistrationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VerificationCodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceKeyHash")
                        .HasFilter("[DeviceKeyHash] IS NOT NULL");

                    b.HasIndex("DevicePublicId")
                        .IsUnique()
                        .HasFilter("[DevicePublicId] IS NOT NULL");

                    b.HasIndex("DeviceId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = N'Active'");

                    b.HasIndex("ObservatoryId", "Status");

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceRigProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DevicePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObservatoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProfileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProfileVersion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObservatoryId");

                    b.HasIndex("DevicePublicId", "Version")
                        .IsUnique();

                    b.HasIndex("RegistrationId", "Version");

                    b.HasIndex("DevicePublicId", "ProfileName", "ProfileVersion", "ProfileSha256");

                    b.ToTable("DeviceRigProfiles", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.Observatory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("LatitudeDegrees")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudeDegrees")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Observatories", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scopes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitor.Common.Security.ApiKey", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralFrame", "Frame")
                        .WithMany("Artifacts")
                        .HasForeignKey("CentralFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactIngestIdentity", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "Artifact")
                        .WithMany("IngestIdentities")
                        .HasForeignKey("CentralArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactLayout", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "Artifact")
                        .WithOne("Layout")
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.CentralArtifactLayout", "CentralArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactProcessingEvidence", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "Artifact")
                        .WithOne()
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.CentralArtifactProcessingEvidence", "CentralArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", "Job")
                        .WithMany()
                        .HasForeignKey("CentralDerivativeJobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactRecipe", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "Artifact")
                        .WithOne("Recipe")
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.CentralArtifactRecipe", "CentralArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifactSource", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "Artifact")
                        .WithMany("Sources")
                        .HasForeignKey("CentralArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "ResolvedArtifact")
                        .WithMany()
                        .HasForeignKey("ResolvedCentralArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artifact");

                    b.Navigation("ResolvedArtifact");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralCaptureControl", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralFrame", "Frame")
                        .WithOne("Control")
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.CentralCaptureControl", "CentralFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralCaptureProfile", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralFrame", "Frame")
                        .WithMany("Profiles")
                        .HasForeignKey("CentralFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.DeviceRigProfile", "DeviceRigProfile")
                        .WithMany()
                        .HasForeignKey("DeviceRigProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeviceRigProfile");

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralCaptureTiming", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralFrame", "Frame")
                        .WithOne("Timing")
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.CentralCaptureTiming", "CentralFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", "PredecessorJob")
                        .WithMany()
                        .HasForeignKey("PredecessorJobId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "ResultArtifact")
                        .WithMany()
                        .HasForeignKey("ResultCentralArtifactId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", null)
                        .WithMany()
                        .HasForeignKey("RetainedResultCentralArtifactId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "SourceArtifact")
                        .WithMany()
                        .HasForeignKey("SourceCentralArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", "SupersededByJob")
                        .WithMany()
                        .HasForeignKey("SupersededByJobId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PredecessorJob");

                    b.Navigation("ResultArtifact");

                    b.Navigation("SourceArtifact");

                    b.Navigation("SupersededByJob");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobAttempt", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", "Job")
                        .WithMany("Attempts")
                        .HasForeignKey("CentralDerivativeJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInput", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("CentralArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", "Job")
                        .WithMany("Inputs")
                        .HasForeignKey("CentralDerivativeJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInputRequirement", "Requirement")
                        .WithOne("Input")
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInput", "CentralDerivativeJobId", "CentralDerivativeJobInputRequirementId")
                        .HasPrincipalKey("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInputRequirement", "CentralDerivativeJobId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Job");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInputRequirement", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", "Job")
                        .WithMany("InputRequirements")
                        .HasForeignKey("CentralDerivativeJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralFrame", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.DeviceRigProfile", "DeviceRigProfile")
                        .WithMany()
                        .HasForeignKey("DeviceRigProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeviceRigProfile");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceFleetState", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.DeviceRegistration", "Registration")
                        .WithOne()
                        .HasForeignKey("HVO.SkyMonitor.LogicHost.Data.DeviceFleetState", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceHeartbeatRecord", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.DeviceRegistration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceRegistration", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.Observatory", "Observatory")
                        .WithMany("DeviceRegistrations")
                        .HasForeignKey("ObservatoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Observatory");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.DeviceRigProfile", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.DeviceRegistration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.ApplicationUser", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralArtifact", b =>
                {
                    b.Navigation("IngestIdentities");

                    b.Navigation("Layout");

                    b.Navigation("Recipe");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJob", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("InputRequirements");

                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralDerivativeJobInputRequirement", b =>
                {
                    b.Navigation("Input");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.CentralFrame", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Control");

                    b.Navigation("Profiles");

                    b.Navigation("Timing");
                });

            modelBuilder.Entity("HVO.SkyMonitor.LogicHost.Data.Observatory", b =>
                {
                    b.Navigation("DeviceRegistrations");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
