<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <ProjectReference Include="..\..\src\HVO.SkyMonitor.Fleet.Contracts\HVO.SkyMonitor.Fleet.Contracts.csproj" />
    <ProjectReference Include="..\..\src\HVO.SkyMonitor.TestSupport\HVO.SkyMonitor.TestSupport.csproj" />
    <Compile Include="..\TestSettings\MSTestSettings.cs" Link="MSTestSettings.cs" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1515;CA1707;CA2007;CA1861;CA1307;CA1859</NoWarn>
  </PropertyGroup>
</Project>
