using System;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Routing;

namespace HVO.SkyMonitor.LogicHost.Components.Layout;

public sealed partial class MainLayoutNavigation : ComponentBase, IDisposable
{
    private static readonly IReadOnlyList<NavigationLink> PublicLinks =
    [
        new NavigationLink("/", "Discover", "bi bi-stars", NavLinkMatch.All),
        new NavigationLink("/observatories", "Observatories", "bi bi-globe-americas", NavLinkMatch.Prefix),
        new NavigationLink("/events", "Events", "bi bi-lightning-charge", NavLinkMatch.Prefix)
    ];

    private static readonly IReadOnlyList<NavigationLink> OperationsLinks =
    [
        new NavigationLink("/app", "Dashboard", "bi bi-grid-1x2", NavLinkMatch.All),
        new NavigationLink("/app/observatories", "Observatories", "bi bi-building-gear", NavLinkMatch.Prefix),
        new NavigationLink("/app/captures", "Captures", "bi bi-images", NavLinkMatch.Prefix),
        new NavigationLink("/app/processing", "Processing", "bi bi-diagram-3", NavLinkMatch.Prefix),
        new NavigationLink("/app/events", "Events", "bi bi-lightning-charge", NavLinkMatch.Prefix)
    ];

    [Inject]
    public NavigationManager NavigationManager { get; set; } = default!;

    private IEnumerable<NavigationLink> PrimaryNavigationLinks => IsOperationsWorkspace ? OperationsLinks : PublicLinks;

    private bool IsOperationsWorkspace { get; set; }

    private string WorkspaceLabel => IsOperationsWorkspace ? "Network Operations" : "Sky Network";

    private string CurrentReturnUrl = string.Empty;

    protected override void OnInitialized()
    {
        UpdateReturnUrl(NavigationManager.Uri);
        NavigationManager.LocationChanged += OnLocationChanged;
    }

    private void OnLocationChanged(object? sender, LocationChangedEventArgs e)
    {
        UpdateReturnUrl(e.Location);
        _ = InvokeAsync(StateHasChanged);
    }

    private void UpdateReturnUrl(string location)
    {
        var baseRelative = NavigationManager.ToBaseRelativePath(location);
        IsOperationsWorkspace = baseRelative.Equals("app", StringComparison.OrdinalIgnoreCase)
            || baseRelative.StartsWith("app/", StringComparison.OrdinalIgnoreCase)
            || baseRelative.StartsWith("devices", StringComparison.OrdinalIgnoreCase);
        CurrentReturnUrl = NormalizeReturnUrl(baseRelative);
    }

    // Keeps logout redirects local and avoids invalid "~//" paths generated by Identity's redirect helper.
    private static string NormalizeReturnUrl(string? baseRelative)
    {
        if (string.IsNullOrWhiteSpace(baseRelative))
        {
            return string.Empty;
        }

        var trimmed = baseRelative.Trim();

        if (trimmed.StartsWith("//", StringComparison.Ordinal)
            || trimmed.StartsWith("\\\\", StringComparison.Ordinal)
            || trimmed.Contains("://", StringComparison.Ordinal))
        {
            return string.Empty;
        }

        if (!Uri.TryCreate(trimmed, UriKind.Relative, out _))
        {
            return string.Empty;
        }

        return trimmed.TrimStart('/');
    }

    public void Dispose()
    {
        NavigationManager.LocationChanged -= OnLocationChanged;
    }


    private static string GetUserDisplayName(ClaimsPrincipal principal)
    {
        return principal.FindFirstValue("name")
            ?? principal.FindFirstValue(ClaimTypes.Name)
            ?? principal.Identity?.Name
            ?? principal.FindFirstValue(ClaimTypes.Email)
            ?? "Account";
    }

    private static string GetUserEmail(ClaimsPrincipal principal)
    {
        return principal.FindFirstValue(ClaimTypes.Email)
            ?? principal.FindFirstValue("preferred_username")
            ?? principal.Identity?.Name
            ?? "unknown";
    }

    private static string GetUserInitials(ClaimsPrincipal principal)
    {
        var displayName = GetUserDisplayName(principal);
        if (string.IsNullOrWhiteSpace(displayName))
        {
            displayName = GetUserEmail(principal);
        }

        var parts = displayName
            .Replace("@", " ", StringComparison.Ordinal)
            .Replace(".", " ", StringComparison.Ordinal)
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        if (parts.Length >= 2)
        {
            return string.Create(2, parts, static (span, source) =>
            {
                span[0] = char.ToUpperInvariant(source[0][0]);
                span[1] = char.ToUpperInvariant(source[^1][0]);
            });
        }

        if (parts.Length == 1 && parts[0].Length >= 1)
        {
            var firstChar = char.ToUpperInvariant(parts[0][0]);
            var secondChar = parts[0].Length > 1 ? char.ToUpperInvariant(parts[0][1]) : firstChar;
            return new string(new[] { firstChar, secondChar });
        }

        return "??";
    }

    private sealed record NavigationLink(string Href, string Label, string IconClass, NavLinkMatch Match);
}
